# Generated by Django 4.2.28 on 2026-03-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alumniabout_vision'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='programs/'),
        ),
    ]
