# Generated by Django 4.2.28 on 2026-03-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_program_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='about',
            field=models.TextField(blank=True, help_text='About the college'),
        ),
        migrations.AddField(
            model_name='college',
            name='goals',
            field=models.JSONField(blank=True, default=list, help_text='Mnemonic goals (e.g., C-A-F)'),
        ),
        migrations.AddField(
            model_name='college',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='college',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
