# Generated by Django 4.2.28 on 2026-03-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_alter_college_about_alter_college_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='about',
            field=models.TextField(blank=True, default='', help_text='About the college', null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='mission',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='vision',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
