# Generated by Django 5.1.4 on 2026-04-09 06:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='about',
            field=models.TextField(blank=True, default='', help_text='About the college section (ABOUT CAF)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='hero_description',
            field=models.TextField(blank=True, default='', help_text='Text for the hero section (ABOUT COLLEGE)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='mission',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='college',
            name='vision',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InquiryReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_sent_to_user', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dashboard.contactmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
