# Generated by Django 5.1.4 on 2026-04-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_college_about_alter_college_hero_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnisuccessstory',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
