# Generated by Django 5.1.4 on 2026-04-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alumnisuccessstory_is_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnisuccessstory',
            name='is_highlighted',
        ),
        migrations.AddField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_publish_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
