# Generated by Django 5.1.4 on 2026-04-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_remove_alumnisuccessstory_is_highlighted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='post',
            name='scheduled_publish_at',
        ),
        migrations.AddField(
            model_name='alumninews',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When to automatically hide/expire the news', null=True),
        ),
        migrations.AddField(
            model_name='alumninews',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When to automatically publish (leave blank for immediate)', null=True),
        ),
        migrations.AlterField(
            model_name='alumninews',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='published', max_length=20),
        ),
    ]
