# Generated by Django 5.1.4 on 2026-04-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_alumni_news_schedule_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When to automatically hide/expire', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When to automatically publish', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled'), ('archived', 'Archived')], default='published', max_length=20),
        ),
    ]
