# Generated by Django 5.1.4 on 2026-04-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_success_story_schedule_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
