# Generated by Django 6.0.4 on 2026-04-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_achievement_expires_at_achievement_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnievent',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When to automatically hide/expire', null=True),
        ),
        migrations.AddField(
            model_name='alumnievent',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When to automatically publish', null=True),
        ),
    ]
