# Generated by Django 5.1.4 on 2026-04-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alumnievent_expires_at_alumnievent_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnievent',
            name='attendees_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='alumnievent',
            name='event_type',
            field=models.CharField(choices=[('Networking', 'Networking'), ('Reunion', 'Reunions'), ('Workshop', 'Workshops'), ('Social', 'Social'), ('Virtual', 'Virtual')], default='Social', max_length=50),
        ),
        migrations.AddField(
            model_name='alumnievent',
            name='is_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
