# Generated by Django 5.1.4 on 2026-04-28 07:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_alumnievent_attendees_count_alumnievent_event_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_mandate', models.TextField(blank=True)),
                ('vision', models.TextField(blank=True)),
                ('mission', models.TextField(blank=True)),
                ('strategic_goals', models.TextField(blank=True)),
                ('core_values', models.TextField(blank=True)),
                ('quality_policy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'University Information',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='alumnievent',
            name='attendees_count',
        ),
        migrations.RemoveField(
            model_name='alumnievent',
            name='event_type',
        ),
        migrations.RemoveField(
            model_name='alumnievent',
            name='is_virtual',
        ),
    ]
