# Generated by Django 5.2.12 on 2026-04-28 20:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0037_universityinfo_remove_alumnievent_attendees_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(choices=[('cas', 'College of Arts and Sciences'), ('cit', 'College of Industrial Technology'), ('cted', 'College of Teacher Education'), ('ccje', 'College of Criminal Justice Education'), ('cba', 'College of Business and Accountancy'), ('caf', 'College of Agriculture and Forestry')], max_length=20, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Profile',
                'verbose_name_plural': 'Admin Profiles',
                'ordering': ['college'],
            },
        ),
    ]
