# Generated by Django 5.2.12 on 2026-05-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_adminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='theme_color',
            field=models.CharField(default='#0078d4', help_text='Theme color for the college (e.g. #2c7f76)', max_length=20),
        ),
    ]
