# Generated by Django 5.2.12 on 2026-05-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_college_theme_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='college',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='college',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='college',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='college',
            field=models.CharField(default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='target_audience',
            field=models.CharField(default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='college',
            field=models.CharField(max_length=50),
        ),
    ]
