# Generated by Codex on 2026-05-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_alter_adminprofile_college_alter_facility_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='college',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
