# Generated by Django 5.2.12 on 2026-05-07 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_alumni_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(default='NORSU BSC', max_length=255)),
                ('address_label', models.CharField(default='Address', max_length=100)),
                ('address_text', models.TextField(default='Bayawan City Campus\nNegros Oriental, 6221')),
                ('phone_label', models.CharField(default='Trunkline', max_length=100)),
                ('phone_number', models.CharField(default='(035) 225-4247', max_length=100)),
                ('email_label', models.CharField(default='Direct Email', max_length=100)),
                ('email_address', models.EmailField(default='norsu_bsc@norsu.edu.ph', max_length=254)),
                ('inquiry_title', models.CharField(default='Direct Inquiry', max_length=255)),
                ('inquiry_description', models.TextField(default='Send a message directly to our campus administration. All inquiries are processed through our central communications portal.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Contact Information',
                'verbose_name_plural': 'Site Contact Information',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
