# Generated by Django 5.2.12 on 2026-05-11 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_sitecontactinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='college',
            field=models.CharField(default='all', max_length=50),
        ),
    ]
