# Generated by Django 5.2.12 on 2026-05-11 07:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_achievement_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='NorsuHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NORSU HISTORY', max_length=255)),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NORSU History',
                'verbose_name_plural': 'NORSU History',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PresidentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DR. NOEL MARJON E. YASI', max_length=255)),
                ('role', models.CharField(default='University President', max_length=255)),
                ('caption', models.TextField(blank=True, default='Information will be updated soon.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='president/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'President Profile',
                'verbose_name_plural': 'President Profiles',
                'ordering': ['-updated_at'],
            },
        ),
    ]
