# Generated by Django 5.2.12 on 2026-05-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_program_college_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='universityinfo',
            name='mission_image',
            field=models.ImageField(blank=True, null=True, upload_to='university-info/'),
        ),
        migrations.AddField(
            model_name='universityinfo',
            name='vision_image',
            field=models.ImageField(blank=True, null=True, upload_to='university-info/'),
        ),
    ]
